[package]
name = "tdt4230"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.10.0"
bytemuck = "1.13.1"
egui = "0.21.0"
egui_glow = { version = "0.21.0", features = ["winit"] }
env_logger = "0.10.0"
glow = "0.12.1"
glutin = "0.30.6"
glutin-winit = "0.3.0"
log = {version = "0.4.17", features = ["max_level_trace", "release_max_level_info"] }
nalgebra-glm = { version = "0.18.0", features = ["convert-bytemuck"] }
raw-window-handle = "0.5.0"
winit = "0.28.2"
